name: "Install helmfile, helm and kubectl"
description: "Install specific versions of helmfile, helm and kubectl"
inputs:
  kubectl-version:
    description: "Version of kubectl"
    required: false
    default: "v1.30.1"
  helm-version:
    description: "Version of helm"
    required: false
    default: "v3.19.0"
  helmfile-version:
    description: "Version of helmfile to install"
    required: false
    default: "0.165.0"
  sops-version:
    description: "Version of sops to install"
    required: false
    default: "v3.7.3"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "download-cloud"
  color: "gray-dark"
