name: 'Install helmfile'
description: 'Installs a specific version of helmfile'
inputs:
  kubectl-version:
    description: "Version of kubectl"
    required: false
    default: "v1.18.0"
  helm-version:
    description: "Version of helm (Helm 2 only)"
    required: false
    default: "v2.16.5"    
  helmfile-version:
    description: 'Version of helmfile to install'
    required: false
    default: 'v0.98.2'
runs:
  using: 'node12'
  main: 'dist/index.js'
