name: 'Install helmfile, helm and kubectl'
description: 'Install specific versions of helmfile, helm and kubectl'
inputs:
  kubectl-version:
    description: "Version of kubectl"
    required: false
    default: "v1.18.5"
  helm-version:
    description: "Version of helm (Helm 2 only)"
    required: false
    default: "v2.16.7"
  helm3-version:
    description: "Version of Helm 3"
    required: false
    default: "v3.2.4"
  helmfile-version:
    description: 'Version of helmfile to install'
    required: false
    default: 'v0.119.0'
  use-helm3:
    description: 'If set to true, Helm 3 get installed instead of Helm 2'
    required: false
    default: "true"
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'gray-dark'
