name: 'Install helmfile, helm and kubectl'
description: 'Install specific versions of helmfile, helm and kubectl'
inputs:
  kubectl-version:
    description: "Version of kubectl"
    required: false
    default: "v1.18.0"
  helm-version:
    description: "Version of helm (Helm 2 only)"
    required: false
    default: "v2.16.7"
  helmfile-version:
    description: 'Version of helmfile to install'
    required: false
    default: 'v0.98.2'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'gray-dark'
