name: 'Install helmfile, helm and kubectl'
description: 'Install specific versions of helmfile, helm and kubectl'
inputs:
  kubectl-version:
    description: "Version of kubectl"
    required: false
    default: "v1.19.3"
  helm-version:
    description: "Version of helm"
    required: false
    default: "v3.7.1"
    deprecationMessage: Will be removed in next release since helm 3 becomes standard.
  helmfile-version:
    description: 'Version of helmfile to install'
    required: false
    default: 'v0.142.0'
  sops-version:
    description: 'Version of sops to install'
    required: false
    default: 'v3.7.1'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download-cloud'
  color: 'gray-dark'
